-- Создание таблицы рейтинга
CREATE TABLE IF NOT EXISTS rating (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

-- Создание таблицы жанров
CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS film (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    release_date DATE NOT NULL,
    duration INT NOT NULL,
    mpa BIGINT NOT NULL,
    FOREIGN KEY (mpa) REFERENCES rating(id)
);

-- Создание таблицы пользователей
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50),
    birthday DATE NOT NULL
);

-- Создание таблицы дружбы
CREATE TABLE IF NOT EXISTS friendship (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    created_at DATE NOT NULL,
    FOREIGN KEY (requester_id) REFERENCES "user"(id),
    FOREIGN KEY (friend_id) REFERENCES "user"(id),
    UNIQUE (requester_id, friend_id)
);

-- Создание таблицы фильмов с жанрами
CREATE TABLE IF NOT EXISTS film_genre (
    film_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genre(id),
    UNIQUE (film_id, genre_id)
);

-- Создание таблицы лайков
CREATE TABLE IF NOT EXISTS film_like (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (film_id) REFERENCES film(id),
    FOREIGN KEY (user_id) REFERENCES "user"(id),
    UNIQUE (film_id, user_id)
);

